//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class author_group
    {
        public long author_group_id { get; set; }
        public long author_id { get; set; }
        public long group_id { get; set; }
    
        public virtual author author { get; set; }
        public virtual group group { get; set; }
    }
}
